apiVersion: v2
appVersion: v0.2.0-beta4
description: Agent Substrate CustomResourceDefinitions.
home: https://github.com/agent-substrate/substrate
keywords:
- agent
- actor
- substrate
- crds
name: substrate-crds
sources:
- https://github.com/agent-substrate/substrate
type: application
version: 0.2.0-beta4
