{{- if and (include "kagent.controller.serviceMonitorEnabled" .) .Values.controller.metrics.secureServing .Values.controller.metrics.serviceMonitor.prometheusServiceAccount.name }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kagent.fullname" . }}-metrics-reader-rolebinding
  labels:
    {{- include "kagent.controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kagent.fullname" . }}-metrics-reader
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controller.metrics.serviceMonitor.prometheusServiceAccount.name }}
    namespace: {{ .Values.controller.metrics.serviceMonitor.prometheusServiceAccount.namespace | default .Values.controller.metrics.serviceMonitor.namespace | default (include "kagent.namespace" .) }}
{{- end }}
