apiVersion: v1
kind: Service
metadata:
  name: agentgateway-api-admin
  namespace: agentgateway-system
spec:
  selector:
    app.kubernetes.io/instance: agentgateway-api
    app.kubernetes.io/name: agentgateway-api
    gateway.networking.k8s.io/gateway-name: agentgateway-api
  ports:
    - name: admin
      port: 15000
      targetPort: 15000
