opentelemetry-collector:
  mode: deployment
  fullnameOverride: otel-collector
  image:
    repository: otel/opentelemetry-collector-contrib
    tag: "0.161.0"
  ports:
    otlp: {enabled: true, containerPort: 4317, servicePort: 4317}
    otlp-http: {enabled: true, containerPort: 4318, servicePort: 4318, nodePort: 30418}
    jaeger-compact: {enabled: false}
    jaeger-thrift: {enabled: false}
    jaeger-grpc: {enabled: false}
    zipkin: {enabled: false}
    metrics: {enabled: true, containerPort: 8889, servicePort: 8889}
  service:
    type: NodePort
  config:
    receivers:
      otlp:
        protocols:
          grpc: {endpoint: 0.0.0.0:4317}
          http: {endpoint: 0.0.0.0:4318}
    extensions:
      health_check: {}
    processors:
      batch: {}
      transform/agentgateway-access-log-body:
        error_mode: ignore
        log_statements:
          - set(log.body, Concat([log.attributes["http.method"], log.attributes["http.path"], log.attributes["protocol"], log.attributes["duration"]], " ")) where log.attributes["gateway"] != nil
    exporters:
      otlp/tempo:
        endpoint: tempo.tempo.svc:4317
        tls: {insecure: true}
      otlphttp/loki:
        endpoint: http://loki-gateway.loki.svc.cluster.local/otlp
    service:
      extensions: [health_check]
      telemetry:
        metrics:
          readers:
            - pull:
                exporter:
                  prometheus: {host: 0.0.0.0, port: 8889}
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/tempo]
        logs:
          receivers: [otlp]
          processors: [transform/agentgateway-access-log-body, batch]
          exporters: [otlphttp/loki]
