apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agentregistry-platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: http://gitea-http.gitea.svc.cluster.local:3000/admin/ai-dlc.git
    targetRevision: main
    path: platform/agentregistry
    helm:
      releaseName: agentregistry
  destination:
    server: https://kubernetes.default.svc
    namespace: agentregistry
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
