apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repository-local-creds.yaml
  - gateway-api-crds.yaml
  - local-platform-repository.yaml
  - kagent.yaml
  - loki-specialist.yaml
  - cloud-native-agents.yaml
  - adk-harness.yaml
  - pi-harness.yaml
  - codex-harness.yaml
  - claude-harness.yaml
  - substrate.yaml
  - agentgateway-platform.yaml
  - agentregistry-platform.yaml
  - tempo.yaml
  - gpu-operator.yaml
  - gitea.yaml
  - llm-runtime.yaml
  - loki-repository.yaml
  - loki.yaml
  - otel-collector.yaml
  - prometheus.yaml
  - grafana.yaml
  - kgateway-platform.yaml
