apiVersion: v1
kind: Secret
metadata:
  name: repo-local-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
stringData:
  enableOCI: "true"
  insecureOCIForceHttp: "true"
  type: helm
  url: registry.registry.svc.cluster.local:5000/charts
