{{- if and (not .Values.useDefaultServiceAccount) .Values.rbac.create }}
{{- include "kagent-tools.rbac.validate" . -}}

{{- if .Values.rbac.namespaces }}
{{- range $namespace := (.Values.rbac.namespaces | uniq | sortAlpha) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  {{- if $.Values.rbac.readOnly }}
  name: {{ include "kagent-tools.fullname" $ }}-read-rolebinding
  {{- else }}
  name: {{ include "kagent-tools.fullname" $ }}-cluster-admin-rolebinding
  {{- end }}
  namespace: {{ $namespace }}
  labels:
    {{- include "kagent-tools.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  {{- if $.Values.rbac.readOnly }}
  name: {{ include "kagent-tools.fullname" $ }}-read-role
  {{- else }}
  name: {{ include "kagent-tools.fullname" $ }}-cluster-admin-role
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "kagent-tools.fullname" $ }}
  namespace: {{ include "kagent-tools.namespace" $ }}
{{- end }}

{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  {{- if .Values.rbac.readOnly }}
  name: {{ include "kagent-tools.fullname" . }}-read-rolebinding
  {{- else }}
  name: {{ include "kagent-tools.fullname" . }}-cluster-admin-rolebinding
  {{- end }}
  labels:
    {{- include "kagent-tools.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  {{- if .Values.rbac.readOnly }}
  name: {{ include "kagent-tools.fullname" . }}-read-role
  {{- else }}
  name: {{ include "kagent-tools.fullname" . }}-cluster-admin-role
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "kagent-tools.fullname" . }}
  namespace: {{ include "kagent-tools.namespace" . }}
{{- end }}

{{- end }}
