apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kagent-tools.fullname" . }}
  namespace: {{ include "kagent-tools.namespace" . }}
  labels:
    {{- include "kagent-tools.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kagent-tools.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kagent-tools.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity: 
      {{- with .Values.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- range . }}
        - {{ toYaml . | nindent 10 | trim  }}
          {{- if not (hasKey . "labelSelector") }}
          labelSelector:
            matchLabels:
              {{- include "kagent-tools.selectorLabels" $ | nindent 14 }}
          {{- end }}
      {{- end }}
      {{- end }}


      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "kagent-tools.serviceAccountName" . }}
      containers:
        - name: tools
          command:
            - /tool-server
          args:
          - "--port"
          - "{{ .Values.service.ports.tools.targetPort }}"
          - "--metrics-port"
          - "{{ .Values.tools.metrics.port | default .Values.service.ports.tools.targetPort }}"
          {{- if .Values.tools.enabledTools }}
          - "--tools={{ join "," .Values.tools.enabledTools }}"
          {{- end }}
          {{- with .Values.tools.args }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.tools.image.registry }}/{{ .Values.tools.image.repository }}:{{ coalesce .Values.global.tag .Values.tools.image.tag .Chart.Version }}"
          imagePullPolicy: {{ .Values.tools.image.pullPolicy }}
          resources:
            {{- toYaml .Values.tools.resources | nindent 12 }}
          env:
            - name: KAGENT_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "kagent-tools.fullname" . }}-openai
                  key: OPENAI_API_KEY
                  optional: true # if the secret is not found, the tool will not be available
            - name: OTEL_TRACING_ENABLED
              value: {{ .Values.otel.tracing.enabled | quote }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.otel.tracing.exporter.otlp.endpoint | quote }}
            - name: OTEL_EXPORTER_OTLP_TRACES_TIMEOUT
              value: {{ .Values.otel.tracing.exporter.otlp.timeout | quote }}
            - name: OTEL_EXPORTER_OTLP_TRACES_INSECURE
              value: {{ .Values.otel.tracing.exporter.otlp.insecure | quote }}
            - name: TOKEN_PASSTHROUGH
              value: {{ (index .Values.tools "k8s" | default dict).tokenPassthrough | default false | quote }}
          {{- with .Values.tools.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http-tools
              containerPort: {{ .Values.service.ports.tools.targetPort }}
              protocol: TCP
            - name: http-metrics
              containerPort: {{ .Values.tools.metrics.port | default .Values.service.ports.tools.targetPort }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: http-tools
            initialDelaySeconds: 15
            periodSeconds: 15
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
