apiVersion: v1
kind: Service
metadata:
  name: {{ include "kagent-tools.fullname" . }}
  namespace: {{ include "kagent-tools.namespace" . }}
  labels:
    {{- include "kagent-tools.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.tools.port }}
      targetPort: {{ .Values.service.ports.tools.targetPort }}
      {{- if eq .Values.service.type "NodePort" }} # Only used if service.type is NodePort
      {{- if .Values.service.ports.tools.nodePort }}
      nodePort: {{ .Values.service.ports.tools.nodePort | default "" }}
      {{- end }}
      {{- end }}
      protocol: TCP
      name: tools
  selector:
    {{- include "kagent-tools.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kagent-tools.fullname" . }}-metrics
  namespace: {{ include "kagent-tools.namespace" . }}
  labels:
    {{- include "kagent-tools.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  selector:
    {{- include "kagent-tools.selectorLabels" . | nindent 4 }}
  ports:
    - name: prometheus-metrics
      protocol: TCP
      port: {{ .Values.tools.metrics.port | default .Values.service.ports.tools.targetPort }}
      targetPort: {{ .Values.tools.metrics.port | default .Values.service.ports.tools.targetPort }}
 