{{- if not .Values.useDefaultServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kagent-tools.fullname" . }}
  namespace: {{ include "kagent-tools.namespace" . }}
  labels:
    {{- include "kagent-tools.labels" . | nindent 4 }}
{{- end }}
