{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agentgateway.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agentgateway.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "agentgateway.name" . }}-role-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "agentgateway.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: agentgateway-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "agentgateway.name" . }}-local-role-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "agentgateway.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: agentgateway-{{ .Release.Namespace }}-local
  apiGroup: rbac.authorization.k8s.io
{{- if .Values.rbac.gatewayNamespaces }}
{{- range (uniq .Values.rbac.gatewayNamespaces) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "agentgateway.name" $ }}-write-role-{{ $.Release.Namespace }}
  namespace: {{ . }}
subjects:
- kind: ServiceAccount
  name: {{ include "agentgateway.serviceAccountName" $ }}
  namespace: {{ $.Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: agentgateway-{{ $.Release.Namespace }}-deployer
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- else }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "agentgateway.name" . }}-write-role-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "agentgateway.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: agentgateway-{{ .Release.Namespace }}-deployer
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
